Name: ecommerceconfig
---
EcommerceConfig:
  folder_and_file_locations:
    - "mysite/_config/ecommerce.yml"

SSViewer:
  theme: main

EcommercePayment:
  supported_methods:
    EcommercePayment_TestSuccess : "Test Success Payment"
    EcommercePayment_TestPending : "Test Pending Payment"
    EcommercePayment_TestFailure : "Test Failure Payment"
    PayPalExpressCheckoutPayment : "Paypal"

PayPalExpressCheckoutPayment:
  test_mode: true
  API_UserName: 'pay-facilitator_api1.sunnysideup.co.nz'
  API_Password: '1377510536'
  API_Signature: 'A28oa-B5R0CTgak6ipR9IK8jr0OoAg01ay9d32LkRH-gEW2FOekonB8q'


OrderStep:
  order_steps_to_include:
    step1: OrderStep_Created
    step2: OrderStep_Submitted
    step3: ElectronicDelivery_OrderStep
    step4: OrderStep_Archived
