Name: ecommerceconfig
---
EcommerceConfig:
  folder_and_file_locations:
    - "mysite/_config/ecommerce.yml"

SSViewer:
  theme: simple

---
Name: testpayments
Only:
  environment: 'dev'
---
EcommercePayment:
  supported_methods:
    EcommercePayment_TestSuccess : "Test Success Payment"
    EcommercePayment_TestPending : "Test Pending Payment"
    EcommercePayment_TestFailure : "Test Failure Payment"
    PayPalExpressCheckoutPayment : "Paypal"

PayPalExpressCheckoutPayment:
  test_mode: true
  API_UserName: 'pay-facilitator_api1.sunnysideup.co.nz'
  API_Password: '1377510536'
  API_Signature: 'A28oa-B5R0CTgak6ipR9IK8jr0OoAg01ay9d32LkRH-gEW2FOekonB8q'


